apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app: mongodb
  annotations:
    description: "MongoDB initialization script"
data:
  mongo-init.js: |
    db.createUser({ user: "admin", pwd: "password", roles: [{ role: "readWrite", db: "mydb" }] });