apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - db-config.yaml
  - db-deploy.yaml
  - db-service.yaml

commonLabels:
  feature: database

nameSuffix: -storage
  

images:
  - name: mongo:latest
    newName: postgres
    newTag: latest