apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depoyment
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: my-api-image:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"