apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - api-deploy.yaml
  - api-service.yaml
  

commonLabels:
  feature: api

nameSuffix: -web

commonAnnotaions:
  verbose: debugging